# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PointSdk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'PointSDK', :git => 'git@github.com:agencyenterprise/point-sdk-ios.git', :branch => 'development'
end
